---
- hosts: all
  become: true
  vars:
    path_script_source: /var/lib/jenkins/workspace/project/
    path_script_destination: /tmp/
    name_script: script.sh
    name_result: result.html

  tasks:
    - name: Copy script 
      ansible.builtin.copy:
        src: "{{ path_script_source }}{{ name_script }}"
        dest: "{{ path_script_destination }}{{ name_script }}"
        mode: '0777'
        
    - name: Execute script
      shell: 
        cmd: /tmp/script.sh

    - name: Download file from Remote Machine to Local ansible-node directory
      become: yes
      fetch:
        src: /tmp/result.html
        dest: /var/lib/jenkins/workspace/project/
        flat: yes
   
   
