---
- hosts: all
  become: true
  tasks:
  - name: Log into DockerHub
    docker_login:
      username: varavkoyv
      password: dckr_pat_1ec_MrbpkTiEH_fFRtXjQvkhaco
  - name: 111
    apt:
      update_cache: yes
      state: latest
      name: python3-pip
  - name: 222
    pip:
      name: docker
  - name: Pull Flask app  image
    docker_image:
      name: varavkoyv/new
      tag: latest
      state: present 
