---
- hosts: all
  become: true
  tasks:
    - name: Copy script 
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/project/script.sh
        dest: /tmp/script.sh
        mode: '0777'
        
    - name: Execute script
      shell: 
        cmd: /tmp/script.sh
      register: result

    - name: Show result
      debug:
        msg: "{{ result.stdout }}"
   
   
