---
- hosts: all
  become: true
  tasks:
  - apt:
    update_cache: yes
    state: latest
    name: python3-pip
  - pip:
    name: docker
  - name: Pull Flask app  image
    docker_image:
      name: varavkoyv/new
      tag: latest
      state: present 
