---
- hosts: all
  become: true
  tasks:
  - name: install docker
    apt:
      update_cache: yes
      state: latest
      name:
      - docker


  - name: 111
    apt:
      update_cache: yes
      state: latest
      name: python3-pip
  - name: 222
    pip:
      name: docker

  - name: login to registry
    shell: "docker login  -p dckr_pat_1ec_MrbpkTiEH_fFRtXjQvkhaco -u varavkoyv"
  
