name: Push Docker image to Docker Hub !!
on:
  push:
    branches: [ "main" ]

jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: "192.168.1.133"
        username: "lever"
        key: ${{ HOST_SSH }}
        port: "22"
        command_timeout: 30m
        script: | 
          echo "Nice Job!!!"
