name: Push Docker image to Docker Hub !1
on:
  push:
    branches: [ "main" ]
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    #timeout-minutes: 5
    steps:

    - name: Run command on remote server
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            echo '--- START WORK ON REMOTE SERVER ---';
            ls -al;
            echo '--- GIT INFORMATION ---'
            git co dev;
            git pull;
            echo '--- DOCKER OPERATIONS ---';
            docker-compose down;
            echo '--- LIST OF DOCKER CONTAINERS AFTER STOPING DOCKER CONTAINERS ---';
            docker ps;
            docker-compose --file docker-compose.prod.yml up -d;
            docker system prune --all --force;
            echo '--- LIST OF DOCKER CONTAINERS AFTER STARTING DOCKER CONTAINERS ---';
            docker ps;

