on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    #- name: Install SSH Key
      #uses: shimataro/ssh-key-action@v2
     # with:
        #key: ${{ secrets.SSH_PRIVATE_KEY }}
       # known_hosts: ${{ secrets.KNOWN_HOSTS }}
   # - name: Adding Known Hosts
   #   run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
    #- name: Deploy with rsync
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" ./deploying/docker/docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/lever
