name: build_push_deploy

on:
  push:
    branches:
     - main
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:

     - name: Step 1
       run: |
          echo "action_state=yellow" >> $GITHUB_ENV
          echo "State is: '${{ env.action_state }}'" # No output since same step
     - name: Step 2
       run: |
          echo "State is: '${{ env.action_state }}'" # Output works
          ${{ env.action_state }}

     - name: Notify Telegram on failure
       if: failure()
       run: |
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=GitHub Action failed for repository ${{ github.repository }} (commit ${{ github.sha }} on branch $BRANCH_NAME). ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} user ${{ github.actor }}" \
          -d "reply_to_message_id=${{ secrets.TOPIC_ID }}" 
