name: new
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Execute Ansible Playbook
      # You may pin to the exact commit or the version.
      # uses: saubermacherag/ansible-playbook-docker-action@6504ab82647581a928477ecb9c6d52f11fc6843f
      uses: saubermacherag/ansible-playbook-docker-action@v1.4
      with:
        # Name of the playbook in your workspace.
        playbookName: ./ansible/script.yaml
        # Name of the inventory file to use.
        inventoryFile: ./ansible/inventory             
