name: new
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Execute Ansible Playbook

      uses: saubermacherag/ansible-playbook-docker-action@v1.4
      with:
        # Name of the playbook in your workspace.
        playbookName: ./ansible/script.yaml
        # Name of the inventory file to use.
        inventoryFile: ./ansible/inventory             
