name: new
on:
  push:
    branches: [ "main" ]
build-container:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      variables:
        image_tag: "$CI_REGISTRY_IMAGE"
      changes:
        - Dockerfile
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      variables:
        image_tag: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      changes:
        - Dockerfile
  services:
    - docker:18-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t ${image_tag} .
    - docker push ${image_tag}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Execute Ansible Playbook

      uses: saubermacherag/ansible-playbook-docker-action@v1.4
      with:
        # Name of the playbook in your workspace.
        playbookName: ~/ansible/script.yml
        # Name of the inventory file to use.
        inventoryFile: ~/ansible/inventory             
